# Change these first
owner: Tech-Phantoms # Your GitHub organization or username, where this repository lives
repo: website-status # The name of this repository

sites:
  - name: TechPhantoms website
    url: https://www.techphantoms.co
NOTIFICATION_DISCORD: true
NOTIFICATION_DISCORD_WEBHOOK: false
# NOTIFICATION_DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/840847170064089100/1a_-HHoLr7xw-EBhWjrTG6Q_lgZdC1oMPg0g4JesTgqjDSwyLUw62wipRohn7RyeGzi_

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: techphantoms.co
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/Tech-Phantoms/Tech-Phantoms/master/favicon.ico
  name: Upptime
  introTitle: "**Tech Phantoms** is an open-source community which focuses on tech-hiring, awareness, UX design, and so much more."
  introMessage: "Tech Phantoms is an open tech organization and ❤ to build Open Source software applications. We are powered by one of the [Microsoft Learn Student Ambassadors](https://studentambassadors.microsoft.com/en-US/profile/49532). We want to enable people to adapt and change technology according to their own ideas and needs and validate science and knowledge through an Open Access approach. It's launched by dedicated efforts of two undergraduate students and a fully functional core team. We also organize events, make mentoring sessions, and so much more."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/Tech-Phantoms/Tech-Phantoms

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
